### ISSUE TITLE
Support Centralized Control Center in cp-ansible

### ISSUE THREAD

**Issue by jernster-clgx** [confluentinc/cp-ansible#233] opened 2020-03-24 21:50 UTC
It'd be nice if there was functionality to support a centralized control center model in cp-ansible.

We currently deploy clusters in GCP with all components using self signed certificates and set our kafka clusters kafka_broker properties confluent.metrics.reporters.bootstrap.servers to point to the brokers of our centralized c3 cluster (zk/brokers/control center).

The challenge with this is that in order for our metrics and other component integration to work (connect, ksql, etc) in our centralized c3, we have to add the c3 cluster caroot into the truststore of our other clusters' host truststore's and add the other clusters caroot into the control center host's truststore file.  This is a manual/tedious task without writing separate playbooks to do this for us post cluster provisioning (which we're likely to do in the mean time).

One thing I did try was copying an existing clusters .crt and .key file for the other clusters to use when provisioning the others but the serial number of the caroot in the newly created clusters truststore file didn't match up - I'm thinking this might be due to using different truststore/keystore credentials than the other clusters, but we've decided not to use the same credentials for truststores/keystores across all of our clusters.

I'm hoping that eventually using commercially signed certificates helps alleviate this challenge but I think this functionality using self signed certs would be nice as well.

**Comment by JumaX** [comment] 2020-03-30 10:26
Hello @jernster Thanks for the request.

Let me start by confirming the following:

1. Our self signed certificates, that we can autogenerate for you, are not designed to be used in production, but merely for standing up your first single test cluster/example of how you can setup TLS.

2. Multi-cluster C3 is also not supported by the playbooks at this time, but it something we are looking into for the future. 

3. The behaviour you are seeing is expected due to how TLS works.

**Let's drill into why this is expected behaviour:**

Reading into this, the behaviour you describe is expected and is not specific to CP-Ansible.  TLS requires that the RootCA is present, or that there is a suitable chain to the RootCA via Intermediate CA's which point back to the RootCA.  This is how TLS validates that the certificates are valid.

The CA has a unique encryption key which it uses to sign all certificates.  When a TLS request is made, either one way or two way, the public cert provided by one side of the connection, needs to be validated against the CA by the other side.  Because you have setup different clusters with different CAs, they are not able to validate the certificates without the other CA being present. 

A bad analogy, it would be like having an American Drivers license, and asking the UK government to validate/renew it.  The UK government did not issue it, so has no idea/authority to do such a thing.  In this instance the US Government is one CA, while the UK Government is another CA. :)

Typically and organization will have a process for generating certificates from a standard CA, thus making sure all certs can be validated across environments, clusters, applications, etc.  If it's a large organization, it may have its own internal CA, where as a smaller organization may use something like "Let's Encrypt".  

https://letsencrypt.org/

**How we can address this currently:**

We provide the following additional mechanisms besides self signed certs:

1. You can provide cp-ansible with certificates, CA, and private key for each host, generated by the same CA

2. You can provide cp-ansible with keystores/truststores which already contain the above, and we can distribute those for you.

For options 1 and 2, that would mean generating a CA, generating self signed certificates for all hosts across all clusters, from the same CA, and then either giving cp-ansible the certs, or putting them into keystores/truststores and providing those.

You could take some of our existing code in the SSL role to do this.

3. You can manually insert the CA certs, from each cluster, into every other clusters truststores.  You will need to do this on every host.

A command similar to the following should work:

`keytool -noprompt -keystore {{path to existing .truststore.jks}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file {{path to your root ca}} \
      -storepass {{truststore_storepass}} \
      -keypass {{truststore_storepass}} `

**Future work:**

We will investigate support multi-cluster C3 with self signed certificates in the future.  Understand, this is not a promise to implement, as its bad practice to run with self signed certificates in any meaningful way.

If anything in the above isn't clear, please don't hesitate to let me know.

**Comment by domenicbove** [comment] 2020-10-05 17:51
We have added centralized control center support to our backlog. There should be a solution for the self signed certs, we will have to investigate during implementation.

**Comment by domenicbove** [comment] 2021-05-04 16:26
@jernster-clgx So in 6.1.0, cp-ansible stopped recreating the ca cert used with the self signed certs option. This means if you install 2 kafka clusters with `ssl_enabled: true` then they will both have their certs signed by the same ca, and that ca will be in c3's truststore.

What you'll need to do is use `control_center_custom_properties` to hook up missing kafka's into c3. All in all this should work with the custom properties feature and now that the ca's don't change on subsequent runs on cp-ansible

**Comment by domenicbove** [comment] 2021-05-04 16:27
Feel free to reopen if you need more help!

**Closed by domenicbove** 2021-05-04 16:26 UTC
Labels: enhancement, help wanted
