### ISSUE TITLE
Non deterministic zookeeper.properties and myid files generation

### ISSUE THREAD

**Issue by michalklempa** [confluentinc/cp-ansible#77] opened 2019-01-31 16:30 UTC
Using these roles, the `zookeeper.properties` and `myid` files are generated non-deterministically.

The list of hosts in group `zookeeper` is in fact not a list, but a dictionary (hash) in Ansible(Python) (see somewhat related https://github.com/ansible/ansible/issues/35495). 
So the code for `myid.j2` (https://github.com/confluentinc/cp-ansible/blob/5.1.x/roles/confluent.zookeeper/templates/myid.j2):
```

{% for host in groups['zookeeper'] %}
{% if host == inventory_hostname %}
{{ loop.index }}
{% endif %}
{% endfor %}
```
may generate different results between runs. Moreover, users usually name their servers in a pattern like:
 - zookeeper-01
 - zookeeper-02

And with this code, it may happen that `zookeeper-01` will be set with myid =2 and vice-versa, which is counter-intuitive.

Same issue is with `zookeeper.properties` (https://github.com/confluentinc/cp-ansible/blob/5.1.x/roles/confluent.zookeeper/templates/zookeeper.properties.j2):
```
# Maintained by Ansible
{% for key, value in zookeeper.config.items() %}
{{key}}={{value}}
{% endfor %}
{% for host in groups['zookeeper'] %}
server.{{ loop.index }}={{ host }}:2888:3888
{% endfor %}
```

This code may (and it happend to me) generate this listing:
```
server.1=zookeeper-02:2888:3888
server.2=zookeeper-01:2888:3888
```

**Comment by sknop** [comment] 2019-03-22 13:49
You are correct, I came across the same issue, which is caused by the Python dictionary not preserving the order. 
I propose the following solution:
Add an artificial config item "id" into the hosts file, for example

zookeeper:
  hosts:
   zookeeper-01:
        zookeeper:
            id: 1
   zookeeper-02:
        zookeeper:
            id: 2

and change the zookeeper.properties.j2 in the following way:

# Maintained by Ansible
{% for key, value in zookeeper.config.items() %}
{{key}}={{value}}
{% endfor %}
{% for host in groups['zookeeper'] %}
{% set zookeeper_vars = hostvars[host].get('zookeeper', dict()) %}
{% set id = zookeeper_vars.get('id', loop.index) %}
server.{{ id }}={{ host }}:2888:3888
{% endfor %}

With this change, the old automatic assignment of ids is preserved, but if zookeeper.id is defined, it will be used.

**Comment by JumaX** [comment] 2019-09-03 11:49
@sknop @michalklempa This has been addressed in the latest merged PR, https://github.com/confluentinc/cp-ansible/pull/124

**Closed by JumaX** 2019-09-03 11:49 UTC
